// Example sandboxed E2E spec (generated by obsidian_plugin_e2e).
//
// Everything here runs inside a sandboxed Obsidian started by
// wdio-obsidian-service: your own Obsidian stays untouched and never steals
// focus while this runs.
//
// These three checks hold for ANY plugin, so they are a useful starting point
// rather than a template to copy blindly. Replace the third one with what your
// change actually does — a spec that only proves "it loaded" is what the offline
// smoke test already covers.

import { browser, expect } from "@wdio/globals";

const PLUGIN_ID = process.env.E2E_PLUGIN_ID ?? "{{PLUGIN_ID}}";

describe("{{PLUGIN_NAME}} in a sandboxed Obsidian", () => {
	it("really is Obsidian, not plain Chromium", async () => {
		// The service drives an Obsidian build over CDP, so the session is
		// Chromium underneath — proving it is Obsidian is what makes the rest of
		// this spec meaningful. Also the cheapest way to catch a misconfigured
		// capability (a wrong "wdio:obsidianOptions" silently runs a bare app).
		const version = await browser.getObsidianVersion();
		expect(version).toMatch(/^\d+\.\d+\.\d+/);
	});

	it("loads and registers its plugin instance", async () => {
		const present = await browser.executeObsidian(({ app }, id) => id in app.plugins.plugins, PLUGIN_ID);
		expect(present).toBe(true);
	});

	it("registers something the user can reach", async () => {
		// Not every plugin registers commands: an editor-extension or view-based
		// plugin legitimately registers none, and an assertion demanding a
		// command would fail it for no reason. Assert the disjunction and report
		// what was found, so the failure message says which parts are empty.
		const surface = await browser.executeObsidian(({ app }, id) => ({
			commands: Object.keys(app.commands.commands).filter((commandId) => commandId.startsWith(id)),
			views: Object.keys(app.workspace.viewFactories ?? {}),
			settingTabs: (app.setting?.pluginTabs ?? []).length,
		}), PLUGIN_ID);

		// wdio's `expect` takes exactly one argument — a custom message is NOT the
		// Jest API here. Fail with the shape inlined instead.
		const total = surface.commands.length + surface.views.length + surface.settingTabs;
		if (total === 0) {
			throw new Error(`expected at least one command, view or setting tab, got ${JSON.stringify(surface)}`);
		}
	});

	it("survives a fresh load without captured errors", async () => {
		// A real assertion about the app's own state, not a placeholder: read the
		// plugin instance back after load and make sure it reports healthy.
		const loaded = await browser.executeObsidian(({ app }, id) => Boolean(app.plugins.plugins[id]), PLUGIN_ID);
		expect(loaded).toBe(true);
	});
});
