// Example sandboxed E2E spec (generated by obsidian_plugin_e2e).
//
// Everything here runs inside a sandboxed Obsidian started by
// wdio-obsidian-service: your own Obsidian stays untouched and never steals
// focus while this runs.

import { browser, expect } from "@wdio/globals";

const PLUGIN_ID = process.env.E2E_PLUGIN_ID ?? "{{PLUGIN_ID}}";

describe("{{PLUGIN_NAME}} in a sandboxed Obsidian", () => {
	it("loads and registers its plugin instance", async () => {
		const present = await browser.executeObsidian(({ app }, id) => id in app.plugins.plugins, PLUGIN_ID);
		expect(present).toBe(true);
	});

	it("registers at least one command", async () => {
		const ids = await browser.executeObsidian(({ app }) =>
			Object.keys(app.commands.commands).filter((id) => id.startsWith("{{PLUGIN_ID}}")),
		);
		expect(ids.length).toBeGreaterThan(0);
	});

	it("reports no captured errors from a fresh load", async () => {
		// dev:errors equivalent, read through the app rather than the CLI: the
		// sandbox has no CLI connection to your Obsidian.
		const errors = await browser.executeObsidian(() => {
			const anyWindow = window as unknown as { _dshErrors?: string[] };
			return anyWindow._dshErrors ?? [];
		});
		expect(errors).toEqual([]);
	});
});
