// WebdriverIO + wdio-obsidian-service: end-to-end tests in a SANDBOXED Obsidian.
//
// Generated by obsidian_plugin_e2e. Why this exists: driving the Obsidian CLI
// against the vault you are looking at makes Obsidian switch windows and steal
// your focus on every check. wdio-obsidian-service launches its own Obsidian
// with an isolated user-configuration directory, so your own Obsidian is never
// touched and never comes to the front.
//
// Run:  pnpm run e2e          (all specs)
//       pnpm run e2e:watch    (keep Obsidian open between runs)
//
// The first run downloads its own Obsidian into ./.obsidian-cache (tens of MB)
// and reuses it afterwards. On a slow connection that download can exceed the
// runner's body timeout and fail with UND_ERR_BODY_TIMEOUT: run it again, the
// cache is kept, so progress is not lost. For offline or CI use, pre-seed the
// cache and point cacheDir at it.
//
// SHAPE MATTERS. Every Obsidian option belongs to the capability key
// "wdio:obsidianOptions"; passing vault/plugins as *service* options looks
// plausible but is ignored, and Obsidian then starts WITHOUT this plugin
// installed — the specs fail with "executeObsidian is not a function". The
// service entry itself is just the string "obsidian".

import path from "node:path";
import type { Options } from "@wdio/types";

const E2E_VAULT = "./e2e/vault"; // a copy is made; your notes are never touched

export const config: Options.Testrunner = {
	runner: "local",
	framework: "mocha",
	specs: ["./e2e/specs/**/*.e2e.ts"],
	maxInstances: 1,
	services: ["obsidian"],
	capabilities: [
		{
			browserName: "obsidian",
			// The Obsidian APP version: "latest" tracks what a user most likely
			// runs, "earliest" resolves to the minAppVersion in manifest.json —
			// exactly the compatibility claim the manifest makes. A pinned
			// version string works too.
			browserVersion: process.env.E2E_APP_VERSION ?? "latest",
			// Two flags, both learned the hard way:
			//  · --no-sandbox: Chromium's renderer sandbox cannot start inside
			//    another sandbox (an agent shell, a CI container); its helper
			//    processes abort at startup.
			//  · --headless=new: the test instance must never put a window on
			//    screen. Without it Obsidian flashes into view during every run,
			//    which is interference even though it is not the user's app.
			"goog:chromeOptions": { args: ["--no-sandbox", "--headless=new"] },
			"wdio:obsidianOptions": {
				// "latest" | "earliest" | a specific installer version.
				installerVersion: process.env.E2E_INSTALLER_VERSION ?? "latest",
				// A COPY of the vault is used, so tests never write to your notes.
				vault: E2E_VAULT,
				copy: true,
				// Install the plugin under test from the project directory.
				plugins: ["."],
			},
		},
	],
	cacheDir: path.resolve(".obsidian-cache"),
	// Plain spec reporter. The service also ships an "obsidian" reporter that
	// prints the Obsidian version instead of Chromium's, but it needs the
	// separate wdio-obsidian-reporter package — installing that package and
	// switching this value over is all it takes.
	reporters: ["spec"],
	logLevel: "warn",
	mochaOpts: { ui: "bdd", timeout: 60_000 },
};
