// WebdriverIO + wdio-obsidian-service: end-to-end tests in a SANDBOXED Obsidian.
//
// Generated by obsidian_plugin_e2e. Why this exists: driving the Obsidian CLI
// against the vault you are looking at makes Obsidian switch windows and steal
// your focus on every check. wdio-obsidian-service launches its own Obsidian
// with an isolated user-configuration directory, so your own Obsidian is never
// touched and never comes to the front.
//
// Run:  pnpm run e2e          (all specs)
//       pnpm run e2e:watch    (keep Obsidian open between runs)

import { browser } from "@wdio/globals";
import type { Options } from "@wdio/types";

const PLUGIN_ID = process.env.E2E_PLUGIN_ID ?? "{{PLUGIN_ID}}";
const E2E_VAULT = "./e2e/vault";
const PLUGIN_DIR = "./{{PLUGIN_DIR}}";

export const config: Options.Testrunner = {
	runner: "local",
	framework: "mocha",
	specs: ["./e2e/specs/**/*.e2e.ts"],
	maxInstances: 1,
	// wdio-obsidian-service downloads Obsidian, installs the plugin from a path
	// and starts it with a sandboxed config directory.
	services: [
		[
			"obsidian",
			{
				// "earliest" resolves to the minAppVersion declared in manifest.json,
				// which is exactly the promise the manifest makes.
				appVersion: process.env.E2E_APP_VERSION ?? "earliest",
				installerVersion: process.env.E2E_INSTALLER_VERSION ?? "earliest",
				// Test a copy of the vault: the sandbox never writes to your data.
				vault: E2E_VAULT,
				copy: true,
				plugins: [PLUGIN_DIR],
			},
		],
	],
	capabilities: [{ browserName: "obsidian" }],
	logLevel: "warn",
	reporters: ["spec"],
	mochaOpts: { ui: "bdd", timeout: 60_000 },
	// Keep this in sync with E2E_PLUGIN_ID above.
	before: async () => {
		// Fail fast and loudly if the plugin is not loaded in the sandbox.
		const loaded = await browser.executeObsidian(({ app }, id) => id in app.plugins.plugins, PLUGIN_ID);
		if (!loaded) throw new Error(`plugin "${PLUGIN_ID}" did not load in the sandboxed Obsidian`);
	},
};
